local function registerCustomRawTokens()
	customRawTokens.registerValidTokens({"CONVERT_TO_FIREABLE", "CONVERT_TO_UNFIREABLE", "AMMO_SHELL", "STUCKIN_DAMAGE_MULTIPLIER", "RANGE", "INACCURACY", "GUN", "FIRE_TIME", "SHELL_FILLING_REACTION", "TRANSFER_HANDLE_MATERIAL_TO_PRODUCT_IMPROVEMENT"})
end
